# oil: Oil  Raises error as "oil" is in "boiler" -> duplicate mappings
biomass-gt: Biomass GT
biomass-st: Biomass ST
biomass: Biomass
ch4: CH4
ch4-boiler: CH4 boiler
ch4-bpchp: CH4 backpressure CHP
ch4-demand: CH4 demand
ch4-excess: CH4 excess
ch4-export: CH4 export
ch4-extchp: CH4 extraction CHP
ch4-gt: CH4 GT
ch4-import: CH4 import
ch4-shortage: CH4 shortage
electricity-bev_charging: BEV charging
electricity-curtailment: Curtailment
electricity-demand: El. demand
electricity-electrolyzer: Electrolyzer
electricity-export: El. export
electricity-heatpump_large: Heat pump (DH)
electricity-heatpump_small: Heat pump (domestic)
electricity-import: El. import
electricity-liion_battery: Battery
electricity-pth: res. PtH
electricity-shortage: El. shortage
electricity-transmission: El. transmission
h2-bpchp: H2 backpressure CHP
h2-cavern: H2 cavern
h2-demand: H2 demand
h2-excess: H2 excess
h2-export: H2 export
h2-gt: H2 GT
h2-import: H2 import
h2-shortage: H2 import
heat_central-demand: Heat cen. demand
heat_central-excess: Heat cen. excess
heat_central-shortage: Heat cen. shortage
heat_central-storage: Heat cen. storage
heat_decentral-demand: Heat dec. demand
heat_decentral-excess: Heat dec. excess
heat_decentral-shortage: Heat dec. shortage
heat_decentral-storage: Heat dec. storage
hydro-ror: Hydro ROR
solar-pv: PV
wind-onshore: Wind on
oil: Oil
